# Generated by Django 3.1.5 on 2021-01-15 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20210113_0322'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '패스트캠퍼스 게시글', 'verbose_name_plural': '패스트캠퍼스 게시글'},
        ),
        migrations.AddField(
            model_name='board',
            name='contents',
            field=models.TextField(default='', null=True, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='board',
            name='registered_dttm',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록시간'),
        ),
        migrations.AddField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=128, null=True, verbose_name='제목'),
        ),
        migrations.AddField(
            model_name='board',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fcuser.fcuser', verbose_name='작성자'),
        ),
        migrations.AlterModelTable(
            name='board',
            table='fastcampus_board',
        ),
    ]
